name: 🚀 GenDiff Check

on: [push, pull_request]

jobs:
  build-and-test:
    name: 🛠 Build & 🔍 Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: 🔑 Checkout Code
    
    - name: 🌐 Use Node.js 21
      uses: actions/setup-node@v1
      with:
        node-version: '21'
        
    - name: 📦 Install Dependencies
      run: make install
      
    - name: 🔎 Lint Code
      run: make lint
      
    - name: 📊 Prepare CodeClimate Test Reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: 🧪 Run Tests With Coverage
      run: make test-coverage

    - name: 📊 Send Test Coverage to CodeClimate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_ID }}
      run: |
        ./cc-test-reporter after-build --exit-code $? -t lcov

